### ISSUE TITLE
Would need more space between title and images in cards

### ISSUE THREAD

**Issue by sfnetwork** [custom-cards/vertical-stack-in-card#37]
Not really sure if it's possible or not (or if one of the feature requests already entered is specifically about that) but would it be possible to add space between the title and the first picture cards (see picture, it feels like it should have the same sapce like I'm poiting with the arrow... Does it make sense?
![2018-12-21 15_42_06-window](https://user-images.githubusercontent.com/5288374/50362910-9f920d80-0537-11e9-998f-5fe1be09b960.png)

**Comment by ofekashery** [comment]
Which browser are you using?
