### ISSUE TITLE
SyntaxError: Unexpected keyword 'const'

### ISSUE THREAD

**Issue by soppilif** [custom-cards/vertical-stack-in-card#48]
In the full home assistant log i get this error:

> ERROR (MainThread) [frontend.js.es5.201901211] https://mydomain.duckdns.org:8123/local/vertical-stack-in-card.js?v=v0.1.0:17:0 SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode.

```
my ui-lovelance.yaml:
  - url: /local/vertical-stack-in-card.js?v=v0.1.0
    type: js
```

but my implementation of the type: custom:vertical-stack-in-card works as expected.
Why does this error appear?

**Comment by ofekashery** [comment]
Please make sure you have ``javascript_version: latest`` in your configuration.yaml under ``frontend``.
If you are still having a issue, please reopen this issue.
