### ISSUE TITLE
add custom updater

### ISSUE THREAD

**Issue by h4nc** [custom-cards/vertical-stack-in-card#52]
Could you add this to custom updater?

Would be great!

https://github.com/custom-components/custom_updater

**Comment by ofekashery** [comment]
Hi @h4nc, it's in the main repo of custom cards.
https://github.com/custom-cards/information/blob/master/repos.json

**Comment by ofekashery** [comment]
Hi @h4nc, it's in the main repo of custom cards.
https://github.com/custom-cards/information/blob/master/repos.json
