### ISSUE TITLE
ha-card-border and ha-card-box-shadow

### ISSUE THREAD

**Issue by SeLLeRoNe** [custom-cards/vertical-stack-in-card#53]
Hi there,
I've been using this card for a while and it is very useful, thanks for that!

I was now sstarting to play around with latest configuration for themes that came out I believe with HA version 0.88 which are:
```  # Round corner + Box Shadown
  ha-card-border-radius: '20px'
  ha-card-box-shadow: 3px 3px rgba(0,0,0,0.4)
```

What I have noticed is that whenever I used this card, the corners and the shadows are not showed, it doesn't happen with other cards (even custom).

Here an example, the right column is done using the vertical-stack-in-card:
![image](https://user-images.githubusercontent.com/9599441/54070798-ae49b000-425c-11e9-90b6-6b68740217a2.png)

Thanks
Andrea

**Comment by ofekashery** [comment]
Hi @SeLLeRoNe! Thank for the report, I fixed it in [0.1.2](https://github.com/custom-cards/vertical-stack-in-card/releases/tag/v0.1.2) 😄
