### ISSUE TITLE
In editor lovelace title show not on card

### ISSUE THREAD

**Issue by pepeEL** [custom-cards/vertical-stack-in-card#57]
When i open editor lovelace and when add title to card it is show above card. When close editor show on card correct.
![editor](https://user-images.githubusercontent.com/16692223/57754006-ca028400-76ed-11e9-9e94-7747d1003485.jpg)

**Comment by 3ative** [comment]
@pepeEL Works ok for me - Problem somewhere else maybe?
#
![image](https://user-images.githubusercontent.com/51385971/60757019-d5db3a00-9ffc-11e9-9281-ad7e8dde8c55.png)

**Comment by dannyshaw** [comment]
I had an issue on my mobile of the title not displaying, turned out to be the font color. not sure if it's the same issue but I'll submit my fix as a PR

**Comment by ofekashery** [comment]
Thanks @dannyshaw !!
