### ISSUE TITLE
Title using accent color instead of main color in 2.0

### ISSUE THREAD

**Issue by ThirteenTX** [custom-cards/vertical-stack-in-card#67]
Just updated and now any of my vertical stack in a cards with titles now shows the accent color and not the main color like it did in previous versions. Is there a style option to change this?

**Comment by ThirteenTX** [comment]
Fixed it by putting the title on the card and not the vertical stack.

**Comment by ofekashery** [comment]
Fixed in [0.2.1](https://github.com/custom-cards/vertical-stack-in-card/releases/tag/v0.2.1).
